Adding sequence number functionality, closes #5
thedyze/save-image-extended-comfyui pull request #7
Opened 2023-11-08 08:03 UTC by AlUlkesh

This adds a per-directory sequence number, as discussed in #5.

2023-11-08 18:31 UTC, thedyze requested changes

2023-11-08 18:45 UTC, AlUlkesh commented on save_image_extended.py
> -					file = f'{filename}{delimiter_char}{counter:0{counter_digits}}.png'
Not removed, changed to a version without .png and added at the end, so we don't up with .png.png. However probably a moot point due to the next remark.

2023-11-08 18:45 UTC, AlUlkesh commented on README.md
> +- `sequence_num_digits` - Number of digits used for the sequence number.
That's a good idea with a toggle instead. I'lll get on it.

2023-11-08 18:46 UTC, AlUlkesh commented on assets/example.png
Not by design. The top part is a screenshot from how it looks for me and I pasted your image only to find out you somehow have a wider area. I'll see what I can do.

2023-11-08 18:51 UTC, thedyze commented on assets/example.png
The wider area is simply me stretching the node :)

2023-11-08 18:54 UTC, thedyze commented on save_image_extended.py
> -					file = f'{filename}{delimiter_char}{counter:0{counter_digits}}.png'
Ah, I see now, missed the part at the end before.

2023-11-08 20:00 UTC, AlUlkesh commented
Here's the change to toggle. One more advantage is that this needs a lot less change of the original code:

https://github.com/thedyze/save-image-extended-comfyui/compare/d712114afa75dd61c9dde6c9cb896e8590212f6b...85e2de0dcec44b375fa816da0bf5e644e8891034#diff-a643104020a7483753628b7986091333cf05d458e463cb6b250fa5e6f3acfe42

2023-11-09 16:59 UTC, aegis72 commented
Not part of the issue, but just a comment: It's great to see an awesome, responsive maintainer!

2023-11-09 17:46 UTC, thedyze approved these changes
Looks good!

2023-11-09 17:48 UTC, merged